import type { ContextRowInput, Daypart, LabelInput, MicroActionInput, Mode, StackInput } from './types';

const labelNames: Array<[string, string, string]> = [['energy', 'Energie', 'Energy'], ['sleep', 'Slaap', 'Sleep'], ['gut', 'Darmen', 'Gut'], ['brain', 'Brein', 'Brain'], ['stress', 'Stress', 'Stress'], ['hormones', 'Hormonen', 'Hormones'], ['movement', 'Beweging', 'Movement'], ['skin', 'Huid', 'Skin']];
export const labels: LabelInput[] = labelNames.map(([key, nl, en]) => ({ key, name: { nl, en } }));

const actionData: Array<[string, string, number, string[]]> = [
  ['Hydratatie', 'Hydration', 2, ['energy', 'gut']], ['Box breathing', 'Box breathing', 3, ['stress', 'brain']], ['Ochtendlicht', 'Morning light', 5, ['energy', 'sleep']], ['Nekmobiliteit', 'Neck mobility', 3, ['movement']], ['Intentie zetten', 'Set an intention', 2, ['brain']],
  ['Koude splash', 'Cold splash', 1, ['energy', 'skin']], ['Lichaamsscan', 'Body scan', 5, ['stress']], ['Dankbaarheid', 'Gratitude note', 3, ['brain']], ['Wandeling na eten', 'Post-meal walk', 10, ['gut', 'movement']], ['Schermpauze', 'Screen break', 3, ['brain']],
  ['Eiwitanker', 'Protein anchor', 2, ['energy', 'hormones']], ['Adem verlengen', 'Extended exhale', 4, ['stress', 'sleep']], ['Heup opener', 'Hip opener', 5, ['movement']], ['Benen omhoog', 'Legs up', 8, ['sleep']], ['Cafeïne grens', 'Caffeine cutoff', 1, ['sleep', 'energy']],
  ['Daglichtpauze', 'Daylight pause', 3, ['energy', 'stress']], ['Maaltijd vertragen', 'Slow your meal', 5, ['gut']], ['Schouder rollen', 'Shoulder rolls', 2, ['movement', 'stress']], ['Gedachten parkeren', 'Thought download', 5, ['sleep', 'brain']], ['Avond dimmen', 'Dim the evening', 2, ['sleep']],
  ['Balanshouding', 'Balance stance', 3, ['movement', 'brain']], ['Huid reset', 'Skin reset', 4, ['skin']], ['Buikademhaling', 'Belly breathing', 4, ['gut', 'stress']], ['Power houding', 'Power posture', 2, ['energy']], ['Reflectievraag', 'Reflection prompt', 4, ['brain', 'stress']],
];
export const actions: MicroActionInput[] = actionData.map(([nl, en, durationMin, actionLabels], index) => ({ title: { nl, en }, effect: { nl: `Ondersteunt ${nl.toLowerCase()}.`, en: `Supports ${en.toLowerCase()}.` }, howTo: { nl: `Voer ${nl.toLowerCase()} rustig uit.`, en: `Practise ${en.toLowerCase()} at an easy pace.` }, warning: { nl: 'Stop als dit oncomfortabel voelt.', en: 'Stop if this feels uncomfortable.' }, labels: actionLabels, durationMin, level: index % 5 === 0 ? 'intermediate' : 'beginner' }));

const stackData = [['Rustige start', 'Calm morning', 'regulate', 'stress'], ['Heldere energie', 'Clear energy', 'activate', 'energy'], ['Focusfundament', 'Focus foundation', 'build', 'brain'], ['Avond landing', 'Evening landing', 'recover', 'sleep'], ['Darmritme', 'Gut rhythm', 'regulate', 'gut'], ['Beweegpauze', 'Movement reset', 'activate', 'movement'], ['Veerkracht bouwen', 'Build resilience', 'build', 'stress'], ['Diepe rust', 'Deep recovery', 'recover', 'sleep']] as const;
export const stacks: StackInput[] = stackData.map(([nl, en, functionTag, primaryLabel], index) => ({ title: { nl, en }, description: { nl: `Een praktische routine voor ${nl.toLowerCase()}.`, en: `A practical routine for ${en.toLowerCase()}.` }, coherence: { nl: 'Kleine acties bouwen samen een stabiel ritme.', en: 'Small actions combine into a steady rhythm.' }, suggestedTiming: { nl: index % 3 === 2 ? 'In de avond' : index % 3 === 1 ? 'Rond de middag' : 'Na het opstaan', en: index % 3 === 2 ? 'In the evening' : index % 3 === 1 ? 'Around midday' : 'After waking' }, functionTag, primaryLabel, supportingLabels: primaryLabel === 'brain' ? ['stress'] : ['brain'], level: index > 5 ? 'intermediate' : 'beginner', isPremium: index > 4, isActive: index !== 6 }));

const modes: Mode[] = ['essential', 'essential', 'balanced', 'full']; const dayparts: Daypart[] = ['morning', 'midday', 'evening'];
export function contextRows(stackIndex: number): ContextRowInput[] { return Array.from({ length: 4 }, (_, rowIndex) => ({ microActionId: `action-${(stackIndex * 3 + rowIndex) % actions.length + 1}`, microActionTitle: actions[(stackIndex * 3 + rowIndex) % actions.length].title, stackSortOrder: rowIndex, priorityOrder: rowIndex + 1, isOptional: rowIndex === 3, isActiveByDefault: rowIndex !== 3, includedInMode: modes[rowIndex], daypart: dayparts[stackIndex % 3], durationOverrideMin: null, timingType: rowIndex === 0 ? 'anchor' : rowIndex === 2 ? 'relative' : 'none', startTime: rowIndex === 0 ? (stackIndex % 3 === 2 ? '21:30' : '07:30') : null, endTime: null, relativeToContextId: rowIndex === 2 ? `context-${stackIndex + 1}-2` : null, dependencyText: { nl: rowIndex === 2 ? 'Na de vorige actie.' : '', en: rowIndex === 2 ? 'After the previous action.' : '' }, contextEffect: { nl: 'Ondersteunt deze routine.', en: 'Supports this routine.' }, contextWarning: { nl: 'Pas aan waar nodig.', en: 'Adapt where needed.' }, centreTime: null, elasticityMin: null })); }
